baseurl      = "https://palucki.github.io/"
title        = "dev BLOG"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = "UA-114543867-3 "

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Developer blog theme powered by Hugo"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]


[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Hello Friend NG"
    subtitle = "A simple theme for Hugo"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "hello friend ng"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
[[menu.main]]
    url = "/"
    identifier = "Home"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    identifier = "About"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    identifier = "Posts"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/project/"
    identifier = "Projects"
    name = "Projects"
    weight = 4
	
[[menu.main]]
    url = "/note/"
    identifier = "Notepad"
    name = "Notepad"
    weight = 5


[[menu.icon]]
    url = "mailto:piotrek.palucki@gmail.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/palucki/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/piotr-palucki/"
    name = "fab fa-linkedin"
    weight = 3

[[menu.icon]]
    url = "https://www.upwork.com/freelancers/~010a9057d1126251d5"
    name = "fas fa-briefcase"
    weight = 4

