baseURL = "https://palucki.github.io/"
languageCode = "en-us"
title = "dev BLOG"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = "UA-114543867-3 "

[params]
    author = "piotr palucki"
    description = "Developer blog theme powered by Hugo"
    githubUsername = "#palucki"
    accent = "lightblue"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4
	
[[menu.main]]
    url = "/note/"
    name = "Notepad"
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:piotrek.palucki@gmail.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/palucki/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/piotr-palucki/"
    name = "fab fa-linkedin"
    weight = 3

[[menu.icon]]
    url = "https://www.upwork.com/freelancers/~010a9057d1126251d5"
    name = "fas fa-briefcase"
    weight = 4

